#!/bin/bash 

# User input 
subj=$1 
njobs=$2

subj_suffix=${subj:4}
if [[ ${subj_suffix:0:1} == "P" ]]; then 
    fmriprep_dir=/project/6050199/akhanf/cfmm-bids/data/Peters/pre_post_tle_connectivity/epi_preop_ge/fmriprep_20.1.1
else
    fmriprep_dir=/project/6050199/akhanf/cfmm-bids/data/Peters/pre_post_tle_connectivity/epi_preop_siemens/fmriprep_20.1.1
fi

# Singularity container
SINGULARITY_PREPDWI=$HOME/singularity/bids-apps/khanlab_prepdwi_latest.sif
SINGULARITYENV_OMP_NUM_THREADS=$njobs
SINGULARITYENV_MKL_NUM_THREADS=$njobs

# Run prepdwi
# Distortion correction will be performed separately - current reg_aladin call seems to perform rig+affine even with rigOnly flag set 
singularity exec $SINGULARITY_PREPDWI $HOME/opt/git/prepdwi/prepdwi /scratch/$USER/pre_post_tle_connectivity/preop /scratch/$USER/pre_post_tle_connectivity/preop/derivatives/prepdwi_v0.0.13/ participant --participant_label $subj --no-topup --no-gradcorr --no-bedpost --no-dke --no-distcorr --no-regT1 -w $SLURM_TMPDIR --in_fmriprep_dir $fmriprep_dir

# Remove output 
rm /scratch/$USER/pre_post_tle_connectivity/preop/derivatives/prepdwi_v0.0.13/prepdwi/$subj/dwi/*

# If phase1 (GE), need to rerun eddy because EffectiveEchoSpacing is a string
pushd .
cd /scratch/$USER/pre_post_tle_connectivity/preop/derivatives/prepdwi_v0.0.13/work

# Distortion correction + regT1
cp /scratch/$USER/pre_post_tle_connectivity/preop/$subj/anat/${subj}_desc-preproc_T1w.nii.gz $subj/t1/t1.nii.gz
cp /scratch/$USER/pre_post_tle_connectivity/preop/$subj/anat/${subj}_desc-brain_mask.nii.gz $subj/t1/t1.mask.nii.gz

singularity exec $SINGULARITY_PREPDWI bet /project/6050199/akhanf/cfmm-bids/data/Peters/tle3T_phase1/$subj/anat/${subj}_acq-DESPOT1_T1map.nii.gz $subj/t1/t1map.temp.nii.gz 

singularity exec $SINGULARITY_PREPDWI bet $subj/t1/t1map.temp.nii.gz $subj/t1/t1map.brain.nii.gz -f 0.3 -m

rm $subj/t1/t1map.temp.nii.gz

singularity exec $SINGULARITY_PREPDWI $HOME/opt/git/prepdwi/bin/processDistortCorrectGE uncorrected_denoise_unring_eddy $subj 

singularity exec $SINGULARITY_PREPDWI $HOME/opt/git/prepdwi/bin/processRegT1 uncorrected_denoise_unring_eddy_dc $subj 2

ln -srfvn $subj/dwi/uncorrected_denoise_unring_eddy_dc_regT1 $subj/dwi/processed

singularity exec $SINGULARITY_PREPDWI processCleanupBIDS uncorrected_denoise_unring_eddy_dc_regT1 /scratch/$USER/pre_post_tle_connectivity/preop/derivatives/prepdwi_v0.0.13/ $subj

popd 